### ISSUE TITLE
Is there any way to perform a bulk insert/update (aka merge)

### ISSUE THREAD

**Issue by kevinding0218** [cloud-maker-ai/Nebula#10]
Hello, we're more than happy to see a different version of .Net cosmos SDK here, while our business logic may look for  a way of handling a subset of data with inserting/updating/upserting/deleting action, would you happen to know if that's available with Nebula?

In addition, from this [post](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/6532266-support-document-versioning) where you've mentioned "Nebula could get versioned read/write consistency for entities with a simple version identifier. This gives you un-delete, restore to previous version etc out of the box without needing to use change feed support directly.", is there any code example to show how to use it?

Any additional code example about how to use Nebula with Cosmos would be much appreciated!

Thank you very much!

Best,
Kevin

**Comment by oughton** [comment]
Currently there is no support for bulk document create/update/delete. There is planned support on the road map to support transaction. See: https://github.com/cloud-maker-ai/Nebula/issues/3. With that will come a more efficient mechanism for performing bulk operations as it will allow multiple write operations to be batched and executed inside a stored procedure.

Code examples are still a work in progress but I can point you to: https://github.com/cloud-maker-ai/Nebula/blob/master/Nebula.AspNetCore.Tests/Store/FlowerStore.cs. This project includes Nebula setup in a .NET Core app and an example API controller and store implementation. Note that the public interfaces are well documented so intellisense will help get you started.

Usage examples will be added and enriched over time.

**Comment by kevinding0218** [comment]
Thank you a lot for your sharing!
