### ISSUE TITLE
Adding new version of document updates previous version

### ISSUE THREAD

**Issue by charisk** [cloud-maker-ai/Nebula#15]
In order to manage and use the `@latest` flag, existing documents get updated when a new document is added, which causes the timestamp to change. This is due to the fact that the `@latest` flag needs to be removed from the previous version of a document and added to the new one.

The consequence of this is that we end up losing the information about when a specific version of a document was actually created. It also makes Nebula not truly an append-only store.

**Comment by oughton** [comment]
Instead of removing the latest flag, have you considered adding a timestamp to the Nebula metadata instead?

The 'apend-only' guarantee for Nebula is loosened to allow for framework optimisations. These optimisations are separate to the document content. The document content (i.e., the part the caller is storing) should be append only.

**Comment by charisk** [comment]
Yeah that was the initial solution that came to mind, but thinking back to the append-only approach of Nebula, having to edit documents doesn't feel right. I think it's worth having a discussion about the best way forward, but the way it works now, it means that data managed by Nebula is incorrect.  

The approach I was thinking was:
- Remove the use of the `@latest` flag (slow is better than incorrect!)
- Agree on whether we should use `@latest` flag and/or some other metadata
- Implement whatever changes we agree on

**Comment by oughton** [comment]
The apend only concept that Nebula promotes is not diminished by writing metadata for a document so long as the document is not modified. Where 'document' is the entity that a caller may create, read, update or delete. Additional metadata is stored along with the document to support framework functions. If you consider the framework metadata along with the document to be the bounds of immutability then this is not the purest form of the append-only pattern but as it stands is a useful compromise for supporting more efficient queries and advanced features coming soon.

I'm open to ideas on how we can achieve querying latest without using a flag in this way but it should be considered as part of this issue as this has scope to prevent future features and improvements.

Hello from the Amalfi Coast by the way :-)

**Comment by charisk** [comment]
Hello 🏝 and sorry you got alerted while you're on holiday!

Appreciate that it "depends how you see it", but I wonder if there are ways to stay pure to that approach. @alex-cloud-maker-ai had a similar thoughts as well. 

One way to avoid using a `@latest` flag, could be by having separate documents in the store that hold information like that (a bit like the ConfigRecords). I'm unsure about the implications on querying though so it's something I'd need to spend more time on. 

Removing the `@latest` flag optimisation is the safest/quickest thing I could think of while you're away. It means that our data going forward won't be incorrect, and that gives us time to look at improving the solution.

**Comment by oughton** [comment]
Maintaining a separate 'config' record for every document could work but would have other implications and tradeoffs that would need to be considered.

That, on the surface, appears to be adding another layer of complexity to the current model to achieve changes abstracted from the frameworks users (apart from perhaps a more purist/dogmatic sense of append-only).

Coming up with a plan about how that would work and be used with read and write queries might help convince me though.

Adding another metadata entry to hold the datetime would be similar or perhaps less changes and less destructive than removing the various query optimisations in place.

**Comment by oughton** [comment]
Thinking about this more (by the pool :-D), a separate config record per document to track the latest version would not work in optimising the common use case of search queries such as,

`SELECT * FROM c WHERE c.Colour = 'Red'`

We'd have no way of optimising against cases where there are many versions of documents. That is, where the query is only interested in the latest version of each document being scanned. This is made worse by Cosmos DB not having temp table support and pricing queries based on predicate complexity.

Given this we should raise an issue to track bringing back optimisation of this common use case if that's not covered under this issue.

**Comment by oughton** [comment]
The new NuGet package version that has been released (1.0.3) prevents the `@latest` flag from being added to new documents. This means there will be a breaking change requiring data migration for projects that are on this version when we bring back the optimisation.

I think the best way to manage that is to start a version 1 release branch to support 1.0.X projects and make the master branch feed version 2 of the package. This way we can make it clear that there are breaking changes between the two versions and allow us to not have to roll out automatic data migration code within the framework at the stage. This is something I'd like to avoid at this stage to prevent slowing the feature roadmap.

We can continue to support the version 1.0.X projects by making bug fixes to the version 1 branch. I will continue to release major feature improvements to master (i.e., version 2.X.X).

**Comment by oughton** [comment]
This change will be maintained on the `release/v1` branch. This removal of the `@latest` optimisation have been reverted on master and a fix rolled for document timestamps to support it.

See: https://github.com/cloud-maker-ai/Nebula/issues/17

Closing this issue.
