### ISSUE TITLE
needs ConfigureAwait(false) on all awaiters

### ISSUE THREAD

**Issue by hankbeasley** [cloud-maker-ai/Nebula#21]
xunit integration test are locking up and I think it is because Awaiters do not have ConfigureAwait(false). And or remove .Wait() statements. The combination of not having ConfigureAwait(false) and .Wait() will cause lock ups under some context.

**Comment by oughton** [comment]
I've checked in some changes to remove some of the blocking async calls ([issue-22](https://github.com/cloud-maker-ai/Nebula/issues/22), [42407bc](https://github.com/cloud-maker-ai/Nebula/commit/42407bc44cb8bc397a445285ac73a406f12aab7d)). I'd rather not apply `ConfigureAwait(false)` to all awaiters. 

This should reduce the likelihood of deadlocks in XUnit test runners.

If this doesn't resolve your issue could you please post more details. E.g.,

- Visual Studio version.
- XUnit runner being used to run tests.
- Is it a subset of integration tests that are failing or are all failing?
- Is the local Cosmos DB emulator configuration setup correctly?

**Comment by hankbeasley** [comment]
Thanks for the update. It's actually my xunit integration test on a different project that are deadlocking. Test are excuted via dotnet test on linux. The exact deadlock location is hard to determine as there is not a easy way for me to attach a debugger. I suspect the couple of Wait statements in the nebula library.

I understand not wantung to put configureawait everywhere as it does make a mess but I dont anyway around it if any calling code could possibly use .wait or. result. I think removing .wait would be good enough for me as I do not use .wait myself.

Also, unrelated to this issue,  I believe your async test should return Task as opposed to void.

**Comment by oughton** [comment]
Yes that sounds reasonable. The `Wait()` call should not be there but was used as a work-around at the time. I'll make some changes to remove the `Wait()` call and instead use proper async-await flows.

This will require some minor changes to the application startup to register the stores you're using with Nebula.

It will be something like, 

```csharp
// Nebula setup:
services
    .AddNebula("ServiceName", Configuration)
    .AddNebulaStore<Store1>()
    .AddNebulaStore<Store2>();

// Normal DI of your store classes:
services.AddScoped<Store1>();
services.AddScoped<Store2>();
```

I'll let you know once I've cut the changes and released a new NuGet package.

**Comment by oughton** [comment]
I've made the changes to remove the `Wait()` call in the library. If you take that version you'll need to update your DI service configuration as mentioned to register your stores with Nebula.

Nuget Package: https://www.nuget.org/packages/CloudMaker.Nebula/2.1.0

Let me know if this solves your issue.

**Comment by hankbeasley** [comment]
No more deadlock after your update. Thanks.
